export const DISPLAY_WEBVIEW = 'WEBVIEWS/DISPLAY_WEBVIEW';

export const RELOAD_WEBVIEW = 'WEBVIEWS/RELOAD_WEBVIEW';

export const HIDE_WEBVIEWS = 'WEBVIEWS/HIDE_WEBVIEWS';

export const WEBVIEW_ERROR = 'WEBVIEWS/WEBVIEW_ERROR';
