export const ADD_ACCOUNT = 'APP/ADD_ACCOUNT';
export const REMOVE_ACCOUNT = 'APP/REMOVE_ACCOUNT';

export const UPDATE_SETTINGS = 'APP/UPDATE_SETTINGS';

export const UPDATE_UNREAD_EMAILS = 'APP/UPDATE_UNREAD_EMAILS';

export const SET_ICON_BADGE_VALUE = 'APP/SET_ICON_BADGE_VALUE';
